# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 992464f
_src_path: /home/waylon/git/pytool-template
author_github: waylonwalker
author_name: Waylon Walker
description: learning sql model
package_name: learn-sql-model
package_title: Learn Sql Model
package_title_input: Learn SQL Model
python_package: learn_sql_model

