"""add shoe size

Revision ID: 19d198151caf
Revises: 20da26039edf
Create Date: 2023-05-19 13:41:45.070918

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '19d198151caf'
down_revision = '20da26039edf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hero', sa.Column('shoe_size', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hero', 'shoe_size')
    # ### end Alembic commands ###
