"""add x and y

Revision ID: 3555f61aaa79
Revises: 79972ec5f79d
Create Date: 2023-06-22 15:03:27.338959

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from learn_sql_model.er_diagram import generate_er_diagram, generate_er_markdown
from learn_sql_model.config import get_config



# revision identifiers, used by Alembic.
revision = '3555f61aaa79'
down_revision = '79972ec5f79d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hero', sa.Column('x', sa.Integer(), nullable=False))
    op.add_column('hero', sa.Column('y', sa.Integer(), nullable=False))
    # ### end Alembic commands ###
    generate_er_diagram(f'migrations/versions/{revision}_er_diagram.png')
    generate_er_markdown(f'migrations/versions/{revision}_er_diagram.md', f'migrations/versions/er_diagram_{revision}.png')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hero', 'y')
    op.drop_column('hero', 'x')
    # ### end Alembic commands ###
