"""new

Revision ID: 44fbe5f1a689
Revises: 29ab77485a4d
Create Date: 2023-05-18 11:17:08.071058

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '44fbe5f1a689'
down_revision = '29ab77485a4d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
