"""add x, y, size

Revision ID: e26398d96dd0
Revises: a9bb6625c57b
Create Date: 2023-06-10 18:37:04.751553

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'e26398d96dd0'
down_revision = 'a9bb6625c57b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hero', sa.Column('x', sa.Integer(), nullable=False))
    op.add_column('hero', sa.Column('y', sa.Integer(), nullable=False))
    op.add_column('hero', sa.Column('size', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hero', 'size')
    op.drop_column('hero', 'y')
    op.drop_column('hero', 'x')
    # ### end Alembic commands ###
